SELECT SUM(SALARY) FROM S_HREMPLOYEES sh ;

SELECT MIN(SALARY), MAX(SALARY), AVG(SALARY) FROM S_HREMPLOYEES sh ;

SELECT COUNT(*),JOB_ID  FROM S_HREMPLOYEES sh 
GROUP BY JOB_ID ;

--SELECT COUNT(1),JOB_ID, DEPARTMENT_ID

SELECT SUM(SALARY),JOB_ID
FROM DBO.S_HREMPLOYEES sh
WHERE JOB_ID IS NOT NULL
GROUP BY JOB_ID 
HAVING SUM(SALARY)>20000
ORDER BY JOB_ID  DESC;

SELECT DEPARTMENT, MAX(SALARY) AS MAX_SAL FROM S_HREMPLOYEES sh GROUP BY DEPARTMENT HAVING MAX(SALARY)>20000;

SELECT * FROM S_HREMPLOYEES sh ORDER BY DEPARTMENT, SALARY DESC;