CREATE TABLE dlithe.dbo.SHK_EMP(
EMP_ID INT,
EMP_NAME VARCHAR(20),
EMP_JOB VARCHAR(10)
)

SELECT * FROM SHK_EMP;

TRUNCATE TABLE SHK_EMP;

DROP TABLE SHK_EMP;

CREATE TABLE dlithe.dbo.SHK_EMP(
EMP_ID INT,
EMP_NAME VARCHAR(20),
EMP_JOB VARCHAR(10)
)

SELECT * FROM SHK_EMP;

INSERT INTO SHK_EMP VALUES(1,'SHRAVAN','DB');
INSERT INTO SHK_EMP VALUES(2,'KUMAR','TESTING');
INSERT INTO SHK_EMP VALUES(3,'SHRAVAN','JAVA');

DELETE FROM SHK_EMP WHERE EMP_NAME='SHRAVAN';

INSERT INTO SHK_EMP VALUES(1,'SHRAVAN','DB');
INSERT INTO SHK_EMP VALUES(2,'KUMAR','TESTING');
INSERT INTO SHK_EMP VALUES(3,'SHRAVAN','JAVA');

UPDATE SHK_EMP
SET EMP_NAME='PRAVEEN', EMP_JOB='DOTNET'
--WHERE EMP_ID=3;

INSERT INTO SHK_EMP VALUES(1,'SHRAVAN','DB');
INSERT INTO SHK_EMP VALUES(2,'KUMAR','TESTING');
INSERT INTO SHK_EMP VALUES(3,'SHRAVAN','JAVA');

--ALTER TABLE SHK_EMP RENAME TO SHK_JOB; 

--ALTER TABLE SHK_EMP RENAME COLUMN EMP_ID TO JOB_ID;

EXEC sp_RENAME 'dbo.SHK_EMP.EMP_NAME', 'NAME', 'COLUMN';

EXEC sp_RENAME 'dbo.student.NAME2', 'NAME_123', 'COLUMN';

EXEC SP_RENAME 'DBO.SHK_EMP','SHK_JOB';

SELECT * FROM SHK_JOB;

ALTER TABLE SHK_JOB 
ADD EMP_SAL INT CHECK(EMP_SAL>10000);

ALTER TABLE SHK_JOB 
DROP COLUMN EMP_SAL;

INSERT INTO SHK_JOB VALUES(1,'SS','IT',9000);

ALTER TABLE SHK_JOB DROP CONSTRAINT CHK_SHK_JOB_EMP_SAL CHECK([EMP_SAL]>10000); 

ALTER TABLE SHK_STUDENT 
ADD PACKG INT ;

UPDATE SHK_STUDENT
SET PACKG=10000 WHERE S_ID=101;
UPDATE SHK_STUDENT
SET PACKG=20000 WHERE S_ID>101 AND S_ID<105;
UPDATE SHK_STUDENT
SET PACKG=30000 WHERE S_ID>104;

