SELECT * FROM SHK_LOCATION
SELECT * FROM SHK_DEPARTMENT
SELECT * FROM SHK_EMPLOYEE

SELECT * FROM DLITHE.DBO.S_HREMPLOYEES

SELECT FIRST_NAME FROM S_HREMPLOYEES 

SELECT * FROM S_HREMPLOYEES sh WHERE DEPARTMENT_ID=50;

SELECT * FROM S_HREMPLOYEES sh WHERE EMPLOYEE_ID>=170;

SELECT *FROM S_HREMPLOYEES sh WHERE EMPLOYEE_ID <=120;

SELECT *FROM S_HREMPLOYEES sh WHERE JOB_ID!='IT_PROG';

SELECT * FROM S_HREMPLOYEES sh WHERE MANAGER_ID <>114;

SELECT * FROM S_HREMPLOYEES sh WHERE MANAGER_ID =100 OR MANAGER_ID =102;

SELECT * FROM S_HREMPLOYEES sh WHERE MANAGER_ID = 100 AND DEPARTMENT_ID =50;

SELECT * FROM S_HREMPLOYEES sh WHERE EMPLOYEE_ID BETWEEN 100 AND 105;

SELECT * FROM S_HREMPLOYEES sh WHERE FIRST_NAME  LIKE '%K';

SELECT * FROM S_HREMPLOYEES sh WHERE LAST_NAME NOT LIKE '%C%';

SELECT * FROM S_HREMPLOYEES sh WHERE COMMISSION_PCT IS NULL;

SELECT * FROM S_HREMPLOYEES sh WHERE COMMISSION_PCT IS NOT NULL;

SELECT * FROM S_HREMPLOYEES sh WHERE DEPARTMENT_ID IN (50,60);SELECT * FROM S_HREMPLOYEES sh ;
SELECT * FROM S_HRDEPARTMENTS sh ;
SELECT * FROM S_HRCOUNTRIES sh ;
SELECT * FROM S_HRLOCATIONS sh ;
SELECT * FROM S_HREMP_DETAILS_VIEW shdv ;
SELECT * FROM S_HRJOB_HISTORY shh ;
SELECT * FROM S_HRJOBS sh ;
SELECT * FROM S_HRREGIONS sh ;

SELECT * FROM S_HREMPLOYEES sh WHERE DEPARTMENT_ID IN(
SELECT DEPARTMENT_ID  FROM S_HRDEPARTMENTS sh2 
--WHERE SH.DEPARTMENT_ID = SH2.DEPARTMENT_ID
);

SELECT * FROM S_HREMPLOYEES sh 
WHERE  EXISTS(SELECT DEPARTMENT_ID  FROM S_HRDEPARTMENTS sh2  WHERE SH.COMMISSION_PCT IS NOT NULL 
);
--WHERE  EXISTS(SELECT DEPARTMENT_NAME FROM S_HRDEPARTMENTS sh2);




