CREATE TABLE SHK_DEMO2(
id INT,
name VARCHAR(40),
age INT,
salary INT,
department VARCHAR(20),
place VARCHAR(20)
);

SELECT * FROM SHK_DEMO2 ;

CREATE TABLE SHK_DEMO3(
id INT,
name VARCHAR(25),
age INT,
address VARCHAR(30),
slary INT,
role VARCHAR(20)
);

SELECT * FROM SHK_DEMO3;

SELECT * INTO SHK_EMPLOYEES_NEW 
FROM S_HREMPLOYEES sh 
WHERE 1=2;

SELECT * FROM SHK_EMPLOYEES_NEW ;

CREATE TABLE SHK_DEMO4(
Years INT,
State VARCHAR(20),
HAI	VARCHAR(100),
Operative_Procedure	VARCHAR(30),
Facility_ID	INT,
Facility_Name VARCHAR(50),
Hospital_Category_RiskAdjustment VARCHAR(100),
Hospital_Type VARCHAR(100),
County VARCHAR(50),
Procedure_Count	INT,
Infection_Count INT,
Predicted_Infection_Count FLOAT,
SIR	FLOAT,
FLOATSIR_CI_95_Lower_Limit FLOAT ,
FLOATSIR_CI_95_Upper_Limit	FLOAT,
Comparison VARCHAR(20),	
SIR_2015 FLOAT,
OnTrack_Toward_2020_Goal VARCHAR(50),
Notes VARCHAR(50)
);

ALTER TABLE SHK_DEMO7
ALTER COLUMN Operative_Procedure VARCHAR(100);

ALTER TABLE SHK_DEMO4
ALTER COLUMN Comparison VARCHAR(100);

ALTER TABLE SHK_DEMO4
ALTER COLUMN Facility_Name VARCHAR(200);

SELECT * FROM SHK_DEMO6;

INSERT INTO SHK_DEMO6 VALUES(1,'ABHI',22,'UDUPI',10000,IT);
INSERT INTO SHK_DEMO6 VALUES(2,'ABHI',22,'UDUPI',10000,IT);
INSERT INTO SHK_DEMO6 VALUES(3,'ABHI',22,'UDUPI',10000,IT);

CREATE TABLE SHK_NEW(
id INT,
name VARCHAR(25),
age INT,
address VARCHAR(30),
slary INT,
role VARCHAR(20)
);
INSERT INTO SHK_NEW VALUES(1,'ABHI',22,'UDUPI',10000,'IT,');
INSERT INTO SHK_NEW VALUES(2,'SHEK',23,'UDUPI',20000,'IT,');
INSERT INTO SHK_NEW VALUES(3,'BHAT',24,'UDUPI',30000,'DB,');
UPDATE SHK_NEW SET name='SACHIN' WHERE id=2;
TRUNCATE TABLE SHK_DEMO4 ;
DROP TABLE SHK_DEMO6 ;

SELECT * FROM SHK_NEW;

CREATE TABLE COLUMNSS(
ID INT,
FIRST_NAME VARCHAR(20),
LAST_NAME VARCHAR(20),
LOCATION VARCHAR(30),
EMP_ID INT,
FULL_NAME VARCHAR(40),
F_NAME VARCHAR(20)
);

SELECT * FROM COLUMNSS ;
