SELECT TOP 10 * FROM S_HREMPLOYEES sh ;

SELECT UPPER(FIRST_NAME) FROM S_HREMPLOYEES sh ;

SELECT LOWER(LAST_NAME) FROM S_HREMPLOYEES sh ;

SELECT INITCAP(EMAIL) FROM S_HREMPLOYEES sh ;

SELECT TRIM(FIRST_NAME) FROM S_HREMPLOYEES sh ;

SELECT LTRIM(JOB_ID) FROM S_HREMPLOYEES sh ;

SELECT TRIM(FIRST_NAME) FROM S_HREMPLOYEES sh ;

SELECT LEN(EMAIL) AS LEN FROM S_HREMPLOYEES sh ;

SELECT REPLACE(JOB_ID,'_','@') FROM S_HREMPLOYEES sh ;

SELECT CONCAT(FIRST_NAME,' ',LAST_NAME) AS FULL_NAME FROM S_HREMPLOYEES sh ;

SELECT CHARINDEX('A',FIRST_NAME),EMPLOYEE_ID  AS POSITIONS FROM S_HREMPLOYEES sh ;

SELECT SUBSTRING(EMAIL,2,6), EMPLOYEE_ID FROM S_HREMPLOYEES sh ;

SELECT CASE WHEN DEPARTMENT_ID=50 THEN 'DATABASE'
WHEN DEPARTMENT_ID = 90 THEN 'TESTING'
ELSE FIRST_NAME
END
FROM S_HREMPLOYEES sh ;


SELECT SUBSTRING(EMAIL,1,5),CONCAT(S_NAME,EMAIL)AS SS, LEN(S_NAME) AS LEN FROM SHK_STUDENT;

SELECT  CASE WHEN DEPARTMENT_ID=30 THEN 'IT' 
WHEN DEPARTMENT_ID=50 THEN 'HR'
WHEN (DEPARTMENT_ID=30 )and (SALARY >10000) and (FIRST_NAME != 'David') THEN 'finance'
ELSE 'OTHER'
END AS DNAME
FROM S_HREMPLOYEES;

select case when DEPARTMENT_ID = 60 then 'IT'
when DEPARTMENT_ID = 90 then 'HR'
when DEPARTMENT_ID = 50 and SALARY >10000 and FIRST_NAME  <>'David' then 'finance'
else 'Others'
end as dname, FIRST_NAME, DEPARTMENT_ID 
from dlithe. dbo.S_HREMPLOYEES;

CREATE TABLE SHK_SKS(
ID INT,
NAME VARCHAR(20),
PLACE VARCHAR(30),
);

INSERT INTO SHK_SKS VALUES(1,'PRAVEEN','MANGALORE');
INSERT INTO SHK_SKS VALUES(1,'PRAVEEN','MANGALORE');
INSERT INTO SHK_SKS VALUES(1,'PRAVEEN','MANGALORE');
INSERT INTO SHK_SKS VALUES(2,'DHANUSH','UDUPI');
INSERT INTO SHK_SKS VALUES(2,'DHANUSH','UDUPI');
INSERT INTO SHK_SKS VALUES(2,'DHANUSH','UDUPI');

SELECT * FROM SHK_SKS;

SELECT * FROM S_HREMPLOYEES sh ;

SELECT CASE WHEN DEPARTMENT_ID=90 THEN 'HR'
ELSE 'OTHERS'
END 
FROM S_HREMPLOYEES sh ;

SELECT * FROM SHK_STUDENT2;

SELECT *, SUBSTRING(EMAIL,CHARINDEX('@',EMAIL)+1,LEN(EMAIL)) AS DOMAINS FROM SHK_STUDENT;

SELECT REPLACE(EMAIL,'@','-') FROM SHK_STUDENT;

SELECT *, REPLACE(REPLACE(REPLACE(REPLACE(EMAIL,'@','-'),'.','-'),'&','-'),'$','-') FROM SHK_STUDENT;

