SELECT TOP 10 * FROM S_HREMPLOYEES sh ;

SELECT UPPER(FIRST_NAME) FROM S_HREMPLOYEES sh ;

SELECT LOWER(LAST_NAME) FROM S_HREMPLOYEES sh ;

SELECT INITCAP(EMAIL) FROM S_HREMPLOYEES sh ;

SELECT TRIM(FIRST_NAME) FROM S_HREMPLOYEES sh ;

SELECT LTRIM(JOB_ID) FROM S_HREMPLOYEES sh ;

SELECT TRIM(FIRST_NAME) FROM S_HREMPLOYEES sh ;

SELECT LEN(EMAIL) AS LEN FROM S_HREMPLOYEES sh ;

SELECT REPLACE(JOB_ID,'_','@') FROM S_HREMPLOYEES sh ;

SELECT CONCAT(FIRST_NAME,' ',LAST_NAME) AS FULL_NAME FROM S_HREMPLOYEES sh ;

SELECT CHARINDEX('A',FIRST_NAME),EMPLOYEE_ID  AS POSITIONS FROM S_HREMPLOYEES sh ;

SELECT SUBSTRING(EMAIL,2,6), EMPLOYEE_ID FROM S_HREMPLOYEES sh ;

SELECT CASE WHEN DEPARTMENT_ID=50 THEN 'DATABASE'
WHEN DEPARTMENT_ID = 90 THEN 'TESTING'
ELSE FIRST_NAME
END
FROM S_HREMPLOYEES sh ;