CREATE VIEW SHK_VWEMP
AS
SELECT * FROM SHK_CONTAINER sc ;

SELECT * FROM SHK_VWEMP;

ALTER VIEW SHK_VWEMP 
AS
SELECT * FROM SHK_EMPLOYEE;

SELECT * FROM SHK_VWEMP;

SELECT * FROM SHK_EMPLOYEE;
SELECT * FROM SHK_DEPARTMENT sd ;

INSERT INTO SHK_EMPLOYEE VALUES(7,'KUMAR',22,'UDUPI',6);

UPDATE SHK_VWEMP 
SET EMP_ADDRESS='MANGALORE' WHERE EMP_ID=1;

SELECT * FROM SHK_VWEMP;

INSERT INTO SHK_DEPARTMENT VALUES(5,'PYTHON','CHENNAI');

ALTER VIEW SHK_VWEMP 
AS
SELECT * FROM 
SHK_EMPLOYEE AS S
INNER JOIN SHK_DEPARTMENT AS D
ON S.DEPT_NO = D.DEPT_ID ;

SELECT * FROM SHK_VWEMP;

ALTER VIEW SHK_VWEMP 
AS
SELECT * FROM 
SHK_EMPLOYEE AS S
FULL OUTER JOIN SHK_DEPARTMENT AS D
ON S.DEPT_NO = D.DEPT_ID ;

----3NF-----

CREATE TABLE dlithe.dbo.SHK_DEPARTMENT22(
DEPT_ID INT,
DEPT_NAME VARCHAR(20),
DEPT_LOCATION VARCHAR(50)
);

CREATE TABLE dlithe.dbo.SHK_EMPLOYEE22(
EMP_ID INT ,
EMP_NAME VARCHAR(20),
EMP_AGE INT,
EMP_ADDRESS VARCHAR(50),
DEPT_NO INT FOREIGN KEY(DEPT_NO) REFERENCES SHK_DEPARTMENT(DEPT_ID)
);

INSERT INTO SHK_DEPARTMENT22 VALUES(1,'JAVA','BANGALORE');
INSERT INTO SHK_DEPARTMENT22 VALUES(2,'DOTNET','BANGALORE');
INSERT INTO SHK_DEPARTMENT22 VALUES(3,'DATABASE','BANGALORE');
INSERT INTO SHK_DEPARTMENT22 VALUES(4,'TESTING','BANGALORE');

SELECT * FROM SHK_DEPARTMENT;

INSERT INTO SHK_EMPLOYEE22 VALUES(1,'SACHIN',22,'BANGALORE',1);
INSERT INTO SHK_EMPLOYEE22 VALUES(2,'ABHISHEK',22,'BANGALORE',1);
INSERT INTO SHK_EMPLOYEE22 VALUES(3,'ARUN',22,'BANGALORE',2);
INSERT INTO SHK_EMPLOYEE22 VALUES(4,'ARJUN',22,'BANGALORE',2);
INSERT INTO SHK_EMPLOYEE22 VALUES(5,'SHON',22,'BANGALORE',3);

SELECT * FROM SHK_EMPLOYEE ;

-----2NF----
CREATE TABLE SHK_EMP33(
NAME VARCHAR(20),
ID INT,
DEPT_NAME VARCHAR(10)
);

CREATE TABLE SHK_DEPT33(
DEPT_NAME VARCHAR(20),
DEPT_ID INT,
);
-----1NF------
CREATE TABLE SHK_EMP22(
ID INT,
NAME VARCHAR(20),
DEPT VARCHAR(20),
MOB INT
);
SELECT * FROM SHK_EMP22;
INSERT INTO SHK_EMP22 VALUES( 1,'ARUN,KUMAR','DB',111111111);
INSERT INTO SHK_EMP22 VALUES(1,'ARUN','DB',111111111);
INSERT INTO SHK_EMP22 VALUES(1,'KUMAR','DB',111111111);