CREATE TABLE SHK_CONTAINER(
id INT,
name VARCHAR(100),
age INT,
salary INT,
department VARCHAR(100),
place VARCHAR(100)
);

CREATE TABLE SHK_SEQ_CONTAINER(
id INT,
name VARCHAR(100),
age INT,
salary INT,
department VARCHAR(100),
place VARCHAR(100)
);

SELECT * FROM SHK_SEQ_CONTAINER;

CREATE TABLE SHK_SEQ_CONTAINER2(
id INT,
name VARCHAR(100),
age INT,
salary INT,
department VARCHAR(100),
place VARCHAR(100)
);


SELECT * FROM SHK_SEQ_CONTAINER2;

TRUNCATE TABLE SHK_SEQ_CONTAINER;

CREATE TABLE SHK_EMP(
EMP_ID INT,
NAME VARCHAR(100),
ZIPCODE VARCHAR(100)
);
SELECT * FROM SHK_EMP;