SELECT
*
FROM
	DBO.S_HREMPLOYEES sh
INNER JOIN DBO.S_HRDEPARTMENTS sh2
ON SH.DEPARTMENT_ID=SH2.DEPARTMENT_ID
RIGHT JOIN DBO.S_HRLOCATIONS SH3
ON SH2.LOCATION_ID=SH3.LOCATION_ID
INNER JOIN DBO.S_HRCOUNTRIES SH4
ON SH3.COUNTRY_ID = SH4.COUNTRY_ID 
LEFT JOIN DBO.S_HRREGIONS SH5
ON SH4.REGION_ID =SH5.REGION_ID 
FULL OUTER JOIN DBO.S_HRJOBS SH6
ON SH.JOB_ID=SH6.JOB_ID ;

CREATE TABLE dlithe.dbo.SHK_STUDENT(
S_ID INT PRIMARY KEY,
S_NAME VARCHAR(20) NOT NULL,
DEPT_ID INT,
EMAIL VARCHAR(20) DEFAULT 'ABC@GMAIL.COM'
);

CREATE TABLE dlithe.dbo.SHK_DEPART(
DEPT_ID INT FOREIGN KEY(DEPT_ID) REFERENCES SHK_STUDENT(S_ID),
DEPT_NAME VARCHAR(20),
DEPT_MANAGER VARCHAR(20)
);

INSERT INTO SHK_STUDENT VALUES(101,'SHRAVAN',1);
INSERT INTO SHK_STUDENT VALUES(102,'KUMAR',2,NULL);
INSERT INTO SHK_STUDENT VALUES(103,'SACHIN',2,NULL);
INSERT INTO SHK_STUDENT VALUES(104,'ABHI',2,NULL);
INSERT INTO SHK_STUDENT VALUES(105,'SOORI',3,NULL);
INSERT INTO SHK_STUDENT VALUES(106,'SUDEEP',3,NULL);

UPDATE SHK_STUDENT 
SET EMAIL='ABC@GMAIL.COM';

SELECT * FROM SHK_STUDENT;

INSERT INTO SHK_DEPART VALUES(101,'ECE','SS');
INSERT INTO SHK_DEPART VALUES(102,'CS','SK');
--INSERT INTO SHK_DEPART VALUES(3,'IS','SO');

SELECT * FROM SHK_DEPART;

SELECT * FROM SHK_STUDENT WHERE S_ID>101;

ALTER TABLE SHK_STUDENT 
ADD PACKG INT ;

UPDATE SHK_STUDENT
SET PACKG=10000 WHERE S_ID=101;
UPDATE SHK_STUDENT
SET PACKG=20000 WHERE S_ID>101 AND S_ID<105;
UPDATE SHK_STUDENT
SET PACKG=30000 WHERE S_ID>104;

SELECT  DEPT_ID,SUM(PACKG) FROM SHK_STUDENT 
GROUP BY DEPT_ID
HAVING SUM(PACKG)>10000
ORDER BY DEPT_ID DESC;


SELECT *FROM SHK_STUDENT;
SELECT * FROM SHK_DEPART;

INSERT INTO SHK_STUDENT VALUES(107,'KUMAR',2,'ABC@GMAIL.COM',10000);

SELECT * FROM SHK_STUDENT SH1
INNER JOIN SHK_DEPART SH2
ON SH1.S_ID  =SH2.DEPT_ID;

SELECT * FROM SHK_STUDENT SH1
LEFT JOIN SHK_DEPART SH2
ON SH1.S_ID=SH2.DEPT_ID;

SELECT * FROM SHK_STUDENT SH1
RIGHT JOIN SHK_DEPART SH2
ON SH1.S_ID=SH2.DEPT_ID;

SELECT * FROM SHK_STUDENT SH1
FULL OUTER JOIN SHK_DEPART SH2
ON SH1.S_ID=SH2.DEPT_ID;

CREATE TABLE SHK_ADDRESS(
ZIPCODE VARCHAR(100),
COUNTRY VARCHAR(100),
CITY VARCHAR(100)
);

INSERT INTO SHK_EMP VALUES(1,'SHON','100');
INSERT INTO SHK_EMP VALUES(2,'ROY','100');
INSERT INTO SHK_EMP VALUES(3,'DHANUSH','101');
INSERT INTO SHK_EMP VALUES(4,'PRUTVI','101');
INSERT INTO SHK_EMP VALUES(5,'RAMESH','102');
INSERT INTO SHK_EMP VALUES(6,'KUMAR','102');

INSERT INTO SHK_ADDRESS VALUES('100','INDIA','BANGALORE');
INSERT INTO SHK_ADDRESS VALUES('101','AUSTRALIA','MELBOURNE');
INSERT INTO SHK_ADDRESS VALUES('102','USA','NEW YORK');
INSERT INTO SHK_ADDRESS VALUES('103','RUSSIA','MOSCOW');

SELECT * FROM SHK_EMP AS E
LEFT JOIN SHK_ADDRESS AS A 
ON E.ZIPCODE=A.ZIPCODE;

SELECT * FROM SHK_EMP AS E
RIGHT JOIN SHK_ADDRESS AS A 
ON E.ZIPCODE=A.ZIPCODE;

SELECT * FROM SHK_EMP AS E
INNER JOIN SHK_ADDRESS AS A 
ON E.ZIPCODE=A.ZIPCODE;

SELECT * FROM SHK_EMP AS E
FULL OUTER JOIN SHK_ADDRESS AS A 
ON E.ZIPCODE=A.ZIPCODE;

--CROSS JOIN
SELECT * FROM SHK_EMP,SHK_ADDRESS;
