SELECT * FROM (
SELECT DENSE_RANK() OVER (PARTITION BY  DEPARTMENT_ID ORDER BY SALARY ASC) AS DRNK,SALARY,DEPARTMENT_ID
FROM S_HREMPLOYEES sh
WHERE DEPARTMENT_ID = 90
)X
WHERE DRNK=1

SELECT * FROM (
SELECT DENSE_RANK () OVER (PARTITION BY DEPARTMENT_ID ORDER BY SALARY DESC) AS DRNK,SALARY,DEPARTMENT_ID,HIRE_DATE
FROM DBO.S_HREMPLOYEES sh 
WHERE DEPARTMENT_ID=90
)X
WHERE DRNK=1

SELECT * FROM (
SELECT DENSE_RANK () OVER (PARTITION BY DEPARTMENT_ID ORDER BY HIRE_DATE  ASC) AS DRNK,SALARY,DEPARTMENT_ID,HIRE_DATE
FROM DBO.S_HREMPLOYEES sh 
WHERE DEPARTMENT_ID=90
)X
WHERE DRNK=1;

SELECT * FROM (
SELECT DENSE_RANK () OVER (PARTITION BY DEPARTMENT_ID ORDER BY HIRE_DATE  ASC) AS DRNK,SALARY,DEPARTMENT_ID,HIRE_DATE
FROM DBO.S_HREMPLOYEES sh 
WHERE DEPARTMENT_ID=90
)X
WHERE DRNK=1;

SELECT * FROM (
SELECT DENSE_RANK () OVER (PARTITION BY DEPARTMENT_ID ORDER BY HIRE_DATE  ASC) AS DRNK,SALARY,DEPARTMENT_ID,HIRE_DATE
FROM DBO.S_HREMPLOYEES sh 
--WHERE DEPARTMENT_ID=90
)X
WHERE DRNK=3

--CTE

WITH DE AS
(
SELECT * ,ROW_NUMBER() OVER(PARTITION BY NAME ORDER BY EMP_ID) AS DD
FROM SHK_JOB sj 
)
 DELETE FROM DE 
 WHERE DD>1;

--COPYING 

SELECT * INTO SHK_JOB_NEW
FROM SHK_JOB sj 
WHERE 1=2;

SELECT * FROM SHK_JOB_NEW ;

INSERT INTO SHK_JOB_NEW 
SELECT DISTINCT * FROM SHK_JOB;

SELECT * FROM (
SELECT DENSE_RANK () OVER (PARTITION BY DEPARTMENT_ID ORDER BY HIRE_DATE  ASC) AS DRNK,SALARY,DEPARTMENT_ID,HIRE_DATE
FROM DBO.S_HREMPLOYEES sh 
--WHERE DEPARTMENT_ID=90
)X
WHERE DRNK=3

SELECT * FROM (
SELECT RANK() OVER (PARTITION BY DEPT_ID ORDER BY S_ID ASC)AS DRNK, S_ID,S_NAME,DEPT_ID FROM SHK_STUDENT
)X

CREATE TABLE SHK_ExamResult
(StudentName VARCHAR(70), 
 Subject     VARCHAR(20), 
 Marks       INT
);
INSERT INTO SHK_ExamResult VALUES('DHANUSH',  'Maths',  65);
INSERT INTO SHK_ExamResult VALUES('DHANUSH',  'Science',  80);
INSERT INTO SHK_ExamResult VALUES('DHANUSH',  'english',  70);
INSERT INTO SHK_ExamResult VALUES('SHREYAS',  'Maths', 50);
INSERT INTO SHK_ExamResult VALUES('SHREYAS',  'Science',  70);
INSERT INTO SHK_ExamResult VALUES('SHREYAS',  'english',  90);
INSERT INTO SHK_ExamResult VALUES('SHON',  'Maths',  55);
INSERT INTO SHK_ExamResult VALUES('SHON',  'Science',  60);
INSERT INTO SHK_ExamResult VALUES('SHON',  'english',  89);

SELECT * FROM SHK_ExamResult ;

SELECT *, ROW_NUMBER() OVER(ORDER BY Marks) AS RowNumber FROM SHK_ExamResult;

SELECT *,RANK() OVER(ORDER BY Marks DESC) Ranks FROM SHK_ExamResult;

SELECT * , DENSE_RANK() OVER(ORDER BY Marks ASC) AS Ranks FROM SHK_ExamResult;
--WHERE Subject='Maths' AND Ranks=4;
SELECT * FROM ( SELECT StudentName,Subject, DENSE_RANK() OVER(ORDER BY Marks ASC) AS Ranks FROM SHK_ExamResult
)X
WHERE Subject='Maths' AND Ranks=4;

